---
server:
  port: 8083
  servlet:
    context-path: /groups
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forumdb
    username: root
    password: India@123
  jpa:
    generate-ddl: true
    show-sql: true
    
    